### ISSUE TITLE
refer to super key

### ISSUE THREAD

**Issue by emacsomancer** [mgi/wm#1]
I don't see any examples of referring to the 'super' key (Mod4) along the lines of control, shift, &c. E.g. for setting a prefix key.

**Comment by mgi** [comment]
Hi emacsomancer,

No I didn't put an example for it the README but I've just tried and you can define one like this:
`(define-prefix-shortcut (:mod-4 #\x) (uiop:launch-program "xeyes"))`

Hope this helps.

**Comment by emacsomancer** [comment]
Thanks!
